//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int id_usuario { get; set; }
        public int id_tipoUsuario { get; set; }
        public int DNI { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public int telefono { get; set; }
        public string contraseña { get; set; }
        public Nullable<int> baja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario { get; set; }
    }
}
